server:
  port: 6000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
  instance:
    instance-id: power
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
spring:
  application:
    name: server-power
